version: '3'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: micro_saas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"